name: Flask CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Create virtual environment and install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Print debugging information (optional)
        run: |
          source venv/bin/activate
          echo "Python Version: $(python --version)"
          echo "Installed Packages:"
          pip freeze

      - name: Run Flask app (Test Run)
        run: |
          source venv/bin/activate
          python app.py
